### ISSUE TITLE
attempting to use your package

### ISSUE THREAD

**Issue by mechoriet** [orkhanahmadov/eloquent-repository#23]
php version: 7.4
laravel version: 7.26.0

```
Symfony\Component\ErrorHandler\Error\FatalError
Access level to App\Repositories\CategoriesRepository::entity() 
must be public (as in class Orkhanahmadov\EloquentRepository\EloquentRepository)
```
^ error in browser
and if i made that entity function to public its saying its not compatible with entity() in the EloquentRepository

even if i generated it via the make:repository command i get the same result
```php
<?php

 

namespace App\Repositories;

 

use App\Models\Category;

use Orkhanahmadov\EloquentRepository\EloquentRepository;

 

class CategoriesRepository extends EloquentRepository

{

    /**

     * Defines entity.

     *

     * @return mixed

     */

    protected function entity()

    {

        return Category::class;

    }
```

**Comment by orkhanahmadov** [comment]
Thank you @mechoriet for reporting.

Under the hood, there were some new changes in how repository class gets a model entity, but they were undocumented and "make" command was still using the old approach.

I fixed the issue and just released version [2.2.0](https://github.com/orkhanahmadov/eloquent-repository/releases/tag/2.2.0) with previously undocumented features.

Basically, now there are 3 ways to define repository entities:

1. By returning model entity from `entity()` method. The old approach.
``` php
use App\Models\Category;
use Orkhanahmadov\EloquentRepository\EloquentRepository;

class CategoryRepository extends EloquentRepository
{
    protected function entity()
    {
        return Category::class;
    }
}
```

2. By setting `$entity` property to model entity.
``` php
use App\Models\Category;
use Orkhanahmadov\EloquentRepository\EloquentRepository;

class CategoryRepository extends EloquentRepository
{
    protected $entity = Category::class;
}
```

3. In some cases, if you don't want to create a dedicated repository class for a specific model entity, you can use base `EloquentRepository` class and set entity dynamically by using `setEntity()`

``` php
use App\Models\Category;
use Orkhanahmadov\EloquentRepository\EloquentRepository;

class HomeController extends Controller
{
    public function index(EloquentRepository $repository)
    {
        return $repository->setEntity(Category::class)->get();
    }
}
```

Now by default `make:repository` command will generate new repository classes with the 2nd approach.
