### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by undjike** [orkhanahmadov/eloquent-repository#29]
Incompatible with PHP8. I don't know whether it's only due to the fact that a PHP version is whitelisted in composer.json.

**Comment by orkhanahmadov** [comment]
@undjike Just published version [2.4.0](https://github.com/orkhanahmadov/eloquent-repository/releases/tag/2.4.0) with PHP 8 support

**Comment by undjike** [comment]
Okay great, thanks.
